[Dotnet] Porting over AdoptingIOSDarkMode to dotnet
xamarin/ios-samples pull request #421
Opened 2022-01-03 20:51 UTC by tj-devel709

2022-01-05 17:18 UTC, mandel-macaque requested changes
This does not look like the correct way to port all the samples to dotnet. The are a number of things to deal with:

1. The structure of the samples was to be maintained since it is consumed by a webpage.
2. We need to do all the samples.

We need to add all this work outside of main:

1. Create a branch called dotnet in the repo (I already did so: https://github.com/xamarin/ios-samples/tree/dotnet).
2. Create this same PR but to the correct branch.

I have double check with @dalexsoto and that is what it was described in the task.

2022-01-05 17:37 UTC, tj-devel709 commented
> 1. https://github.com/xamarin/ios-samples/tree/dotnet

@mandel-macaque That makes a lot of sense haha thank you for clarifying that for me!

2022-01-05 17:46 UTC, tj-devel709 commented
Going through the PR now and making the first round of changes from the Improving iOS Sample doc!

2022-01-07 17:05 UTC, mandel-macaque requested changes

2022-01-07 17:05 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/Before Adoption (1)/Before1MoreViewController.cs
> +	UIImageView starImageView = new UIImageView (UIImage.FromBundle ("StarImage"));
Same.

2022-01-07 17:05 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/Before Adoption (1)/Before1MoreViewController.cs
> +	UILabel titleLabel = new UILabel ();
Same.

2022-01-07 17:05 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/Before Adoption (1)/Before1MoreViewController.cs
> +	UIImageView backgroundImageView = new UIImageView ();
Same.

2022-01-07 17:05 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/Before Adoption (1)/Before1MoreViewController.cs
> +	UIVisualEffectView blurView = new UIVisualEffectView ();
Same.

2022-01-12 03:15 UTC, mandel-macaque requested changes

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	}
The entire thing can be re-written in a more modern way:
```suggestion
	UIImageView starImageView = new UIImageView (UIImage.FromBundle ("StarImage")) {
		    TranslatesAutoresizingMaskIntoConstraints = false;
		    // DARK MODE ADOPTION: Changed to a color, from the "After" asset catalog,
		    // which has light and dark variants:
		    TintColor = UIColor.FromName ("LightAndDarkHeaderColor");
	        }
```

Doing the above is going to remove A LOT of the null check. If I am not mistaken, you added the private variable to the nullable because it was not initialised, that cascaded in a collection of null checks needed everywhere when in reality they are not. The suggestion will make your life easier and code cleaner. In the old times, you could not use the property initalizers which resulted in that 2 step init which is ugly ugly.

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	UILabel ConfigureTitleLabel ()
Same.

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	UIImageView ConfigureBackgroundImageView ()
Same

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	UIVisualEffectView ConfigureBlurView (UIBlurEffect blurEffect)
Same

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	UIVisualEffectView? vibrancyView;
Same

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	UILabel? vibrantLabel;
Same

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +		if ( starImageView is null || backgroundImageView is null || titleLabel is null || vibrantLabel is null || blurView is null || vibrancyView is null || View is null)
I would be very surprised if this is needed if you implement the  code as I commented above, probably is not longer needed.

2022-01-12 03:15 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2SlowDrawingViewController.cs
> +		UIColor [] colors = { UIColor.White, UIColor.LightGray, UIColor.Gray, UIColor.FromName ("HeaderColor") ?? UIColor.DarkGray };
<3

2022-01-14 19:52 UTC, mandel-macaque approved these changes
Two small nit comments. What happened with all those '?' and '!' 😮 ?

2022-01-14 19:52 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +	};
```suggestion
	};

```
nit

2022-01-14 19:52 UTC, mandel-macaque commented on dotnet/ios/ios13/AdoptingIOSDarkMode/AdoptingIOSDarkMode/After Adoption (2)/After2MoreViewController.cs
> +			throw new InvalidOperationException ("View");
Use nameof

2022-01-14 20:40 UTC, dalexsoto approved these changes

2022-01-14 22:38 UTC, merged