[Dotnet] Porting SupportingMultipleWindowsOniPad to dotnet
xamarin/ios-samples pull request #422
Opened 2022-01-06 15:50 UTC by tj-devel709

Just a heads up on this sample, running the project as-is will result in a black screen on an ipad simulator both in this project and the original sample here: https://github.com/xamarin/ios-samples/tree/main/ios13/SupportingMultipleWindowsOniPad

The README includes instructions on adding a few lines to the info.plist to make things work found here: https://github.com/xamarin/ios-samples/tree/main/ios13/SupportingMultipleWindowsOniPad#instructions

As Chris pointed out to me, this follows how Apple created there sample here: https://developer.apple.com/documentation/uikit/app_and_environment/scenes/supporting_multiple_windows_on_ipad

2022-01-07 16:13 UTC, chamons approved these changes

2022-01-07 16:13 UTC, chamons commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/SceneDelegate.cs
> +		var userActivities = connectionOptions.UserActivities?.ToArray () ?? new NSUserActivity [0];
Spacing looks wrong here?

2022-01-07 16:13 UTC, chamons commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +using ObjCRuntime;
Needed?

2022-01-07 16:13 UTC, chamons commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +	nfloat itemsPerRow = 5;
Suggestion - Capitalize constants and make const.

const nfloat ItemsPerRow = 5;
const nfloat Spacing = 20;

2022-01-07 17:08 UTC, mandel-macaque requested changes

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/SceneDelegate.cs
> +			if (userActivity == null) {
is over ==

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/SceneDelegate.cs
> +				if (PhotoDetailViewController.LoadFromStoryboard () is PhotoDetailViewController photoDetailViewController) {
Yikes! so many nested if!!! cnan we put them in a single one with an &&?

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		var userActivity = selectedPhoto!.OpenDetailUserActivity ();
What if null?

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		var itemProvider = new NSItemProvider (UIImage.FromFile (selectedPhoto!.Name!)!);
Same.

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		detailViewController!.Photo = selectedPhoto;
What if null?

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		cell!.Image = UIImage.FromFile (photo!.Name!)!;
same.

2022-01-07 17:08 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (Photo != null)
is not over !=

2022-01-07 20:23 UTC, tj-devel709 commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +using ObjCRuntime;
Yeah, this one is not implicitly included and is needed for nfloat

2022-01-07 20:27 UTC, tj-devel709 commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +	nfloat itemsPerRow = 5;
Looks like nfloats cannot be const

2022-01-10 17:18 UTC, mandel-macaque requested changes
Wrong target branch should be main.

2022-01-12 03:25 UTC, mandel-macaque requested changes

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/Models.cs
> +		new PhotoSection {
AFAIK, you can just do new { }.

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryCollectionViewCell.cs
> +			return imageView!.Image!;
@tj-devel709  what happens when you do imageView?.Image? 

With that, your remove the need of the if ;)

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryCollectionViewCell.cs
> +		set => imageView.Image = value;
and what happens here when imageView is null?

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +			throw new NullReferenceException ("selectedPhoto was null");
I'd be surprises GetPhoto returns null, but you added it nullable. what about and out parameter, and move GetPhoto to TryGetPhoto, then make Photo NOT nullable and be happy :) 
```csharp
bool TryGetPhoto (NSIndexPath indexPath, out Photo photo)
```

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		var selectedPhoto = GetPhoto (indexPath);
same.

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		if (photoSections is null)
Make photoSections not nullable and use Array.Empty<> for its initial value and you will not longer need to do the checks :)

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		if (photoSections is null || photoSections[section] is null || photoSections[section].Photos is null)
Same

2022-01-12 03:25 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		var photo = GetPhoto (indexPath);
Same, TryGetPhoto

2022-01-13 15:32 UTC, tj-devel709 commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/Models.cs
> +		new PhotoSection {
It didn't seem to allow this for the new PhotoSection or the new Photo

2022-01-13 20:24 UTC, rolfbjarne requested changes

2022-01-13 20:24 UTC, rolfbjarne commented on dotnet/ios/ios13/TestTest/TestTest/AppDelegate.cs
> +namespace TestTest;
TestTest? This doesn't look like it's coming from an Apple sample.

2022-01-14 17:33 UTC, tj-devel709 commented on dotnet/ios/ios13/TestTest/TestTest/AppDelegate.cs
> +namespace TestTest;
Accidently included this test project! Thanks for catching, should be fixed now!

2022-01-14 20:18 UTC, mandel-macaque requested changes
We can do better nullability and there is a bug.

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryCollectionViewCell.cs
> +			return imageView.Image;
Trick here, since you are allows to return a null, there is not need to do the if, simply use the ? operator and return
```suggestion
			return imageView?.Image;
```

And at that point, we an remove the {} and the return and use =>

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		if (PhotoSections[indexPath.Section]?.Photos?[indexPath.Row] is null)
The line contains a bug. PhotoSections is an array, so if the indexPath is out of the array, you get an array out of bounds exception. 

At that point, we remove the need of the first '?'. 

The second ? is not needed, same thing, is na array, so remove the '?' Compare the size and the the appropriate thing.

So this line has one bug and 2 not need uses of ?

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +			photo = new Photo ();
You are setting the out not to tool to avoid the nullability, but that is not need, there is a nice new attribute for the cases that you can add to the parameter: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullwhenattribute?view=net-6.0

Use that for the out parameter.

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		photo = PhotoSections[indexPath.Section]!.Photos![indexPath.Row];
Follow what I mentioned about indexes and you do not need any of those !

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (View is null || View.Window.WindowScene is null)
invert the if so that we only have one exit point the method, is more readable.

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (View is null || View.Window.WindowScene is null)
same

2022-01-14 20:18 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (View is null || View.Window.WindowScene is null)
invert as in use "is not" and &&

2022-01-14 21:18 UTC, tj-devel709 commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +			photo = new Photo ();
Okay, if I understood this correctly, you are saying to do something like this?
```
	bool TryGetPhoto (NSIndexPath indexPath, [MaybeNullWhen (false)] out Photo photo)
	{
		if (PhotoSections[indexPath.Section].Photos[indexPath.Row] is null)
		{
			photo = null;
			return false;
		}

		photo = PhotoSections[indexPath.Section].Photos[indexPath.Row];
		return true;
	}
```

2022-01-17 09:11 UTC, rolfbjarne approved these changes

2022-01-19 15:50 UTC, mandel-macaque requested changes
We can write some cleaner code.

2022-01-19 15:50 UTC, mandel-macaque commented on dotnet/ios/ios13/AddingTheSignInWithAppleFlowToYourApp/AddingTheSignInWithAppleFlowToYourApp/AppDelegate.cs
> +		vc.View!.AddSubview (new UILabel (Window!.Frame) {
```suggestion
		vc.View?.AddSubview (new UILabel (Window!.Frame) {
```

Rather than tell the compiler to ignore the warning which could result in a NRW use ? which will do nothing if null.

2022-01-19 15:50 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		&& indexPath.Row < PhotoSections[indexPath.Section].Photos.Length) {
Small indentation fix:
```suggestion
		if (indexPath.Section >= 0 && indexPath.Section < PhotoSections.Length && indexPath.Row >= 0
			&& indexPath.Row < PhotoSections[indexPath.Section].Photos.Length) {
```

2022-01-19 15:50 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +			return true;
Can we simplify this? For example, if PhotoSections[indexPath.Section].Photos[indexPath.Row] is null it can be assigned to the out variable nevertheless, then we can return phot is not null
```suggestion
			photo = PhotoSections[indexPath.Section].Photos[indexPath.Row];
			return photo is not null;
```

2022-01-19 15:50 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (Photo is not null && Photo.Name is not null)
You can simplify this, for example with:
```suggestion
		if (Photo?.Name is not null)
```
Why, because if Photo is null we will get null, else we will get Name, which might or not be null

2022-01-19 15:50 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (View is not null && View.Window.WindowScene is not null)
Same comment as above, I leave it for you as an exercise.

2022-01-19 15:50 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (View is not null && View.Window.WindowScene is not null)
Same.

2022-01-19 22:06 UTC, tj-devel709 commented on dotnet/ios/ios13/AddingTheSignInWithAppleFlowToYourApp/AddingTheSignInWithAppleFlowToYourApp/AppDelegate.cs
> +		vc.View!.AddSubview (new UILabel (Window!.Frame) {
Oh man, this isn't even the right project.. Rolf pointed out that I added a test project when I created this PR but I guess I also included this one...

2022-01-19 22:07 UTC, tj-devel709 commented on dotnet/ios/ios13/AddingTheSignInWithAppleFlowToYourApp/AddingTheSignInWithAppleFlowToYourApp/AppDelegate.cs
> +		vc.View!.AddSubview (new UILabel (Window!.Frame) {
Okay, Just looked at all the files and it seems that there aren't any more accidentally added projects...

2022-01-19 22:15 UTC, tj-devel709 commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/PhotoDetailViewController/PhotoDetailViewController.cs
> +		if (Photo is not null && Photo.Name is not null)
Ah I like this trick haha

2022-01-20 22:23 UTC, mandel-macaque approved these changes
Minor question.

2022-01-20 22:23 UTC, mandel-macaque commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		&& indexPath.Row < PhotoSections[indexPath.Section].Photos.Length) {
Was this done? I see the same indentation

2022-01-21 21:49 UTC, tj-devel709 commented on dotnet/ios/ios13/SupportingMultipleWindowsOniPad/Gallery/View Controllers/GalleryViewController/GalleryViewController.cs
> +		&& indexPath.Row < PhotoSections[indexPath.Section].Photos.Length) {
Private messaged but yes, I deleted the indent and shows in the code file for me!

2022-01-24 14:29 UTC, merged