Update for DisablingPullingDownASheet for dotnet6
xamarin/ios-samples pull request #423
Opened 2022-01-06 21:36 UTC by stephen-hawley

dotnet6 port

For the most part, this required:
- using top level namespace declarations
- ensuring that locals are initialized to something useful
- null checks for things that can be null

2022-01-06 21:48 UTC, chamons commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/DisablingPullingDownASheet.csproj
> +  </PropertyGroup>
Remove codesign args.

Do we need these two groups? I thought MtouchDebug was set by default? Did the template give you this?

2022-01-06 21:49 UTC, stephen-hawley commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/DisablingPullingDownASheet.csproj
> +  </PropertyGroup>
Will do. As far as the rest goes, it's just what was created.

2022-01-06 22:01 UTC, tj-devel709 commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/AppDelegate.cs
> +﻿using Foundation;
I think most, if not all, the using statements in this project can be removed since they are already implicitly included in the dotnet project: https://dotnetcoretutorials.com/2021/08/31/implicit-using-statements-in-net-6/

2022-01-07 17:10 UTC, mandel-macaque requested changes

2022-01-07 17:10 UTC, mandel-macaque commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/EditViewController.cs
> +	}
Auto property?

2022-01-07 17:10 UTC, mandel-macaque commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/EditViewController.cs
> +		if (alert.PopoverPresentationController != null)
is over ==

2022-01-10 17:15 UTC, mandel-macaque requested changes
Wrong target branch, should be dotnet, not main.

2022-01-12 03:35 UTC, mandel-macaque requested changes
Looks good, minor changes to get it to look more modern :)

2022-01-12 03:35 UTC, mandel-macaque commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/EditViewController.cs
> +	public bool HasChanges { get => OriginalText != EditedText; }
You can rewrite this without the get in the new C#
```suggestion
	public bool HasChanges  => OriginalText != EditedText;
```

2022-01-12 03:35 UTC, mandel-macaque commented on dotnet/ios/ios13/DisablingPullingDownASheet/DisablingPullingDownASheet/RootViewController.cs
> +					break;
Lets use the is operator to do all this rather than as + a check against null, this was added after c# 7: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is

2022-01-12 16:43 UTC, mandel-macaque approved these changes

2022-01-12 20:15 UTC, merged