[Dotnet] Porting UsingCollectionViewCompositionalLayoutsAndDiffableDataSources
xamarin/ios-samples pull request #425
Opened 2022-01-07 01:13 UTC by tj-devel709

The first commit has the initial copying over from the legacy project and the second commit has almost all the updating and cleaning. I also made a change fixing the legacy sample's background in the TableViewEditingViewController.cs which was showing up as transparent.

If I could get some extra eyes on the nullable stuff!

There is another issue I found in the legacy sample where the UIImageView inside ConferenceVideoCell.cs does not render. I attempted to fix this issue but could not get it to work properly. Issue created here: https://github.com/xamarin/ios-samples/issues/424

2022-01-07 16:47 UTC, chamons approved these changes

2022-01-07 16:47 UTC, chamons commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +		Section (int value) => Value = value;
Though technically correct, I prefer blocks for variable setting. Not sure if there is a mono coding standard here.

Section (int value)
{
    Value = value;
}

2022-01-07 16:47 UTC, chamons commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +		foreach (var section in sections) {
Nit: I'm not sure this is better than a good old for loop, but not worth rewriting.

2022-01-07 16:47 UTC, chamons commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Basics View Controllers/DistinctSectionsViewController.cs
> +		return section is not null ? new UICollectionViewCompositionalLayout(SectionProviderHandler!) : null;
Why do we create a variable for one use here? It's not captured in the static function or reused fwict?

2022-01-07 16:47 UTC, chamons commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Basics View Controllers/PinnedSectionHeaderFooterViewController.cs
> +	static readonly string sectionHeaderElementKind = nameof (sectionHeaderElementKind);
Should statics be capitalized?

2022-01-07 17:18 UTC, mandel-macaque requested changes
I don't think we should be abusing the ! operator. We can check for null and then do the appropriate, using ! everywhere is line not using nullable enabled.

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/AppDelegate.cs
> +	}
Why a nested class?

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +		collectionView = new UICollectionView (View!.Bounds, CreateLayout ()) {
What if null?

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +			// Populate the cell with our item description.
What if null? Can we just do the check with an is not and then not ignore anything?

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollBehaviorViewController.cs
> +		public static SectionKind None { get; } = new SectionKind (5, nameof (None));
public? is that needed?

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollBehaviorViewController.cs
> +			return Unknown;
Can this with done with a switch? I believe is possible.

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollBehaviorViewController.cs
> +			return UICollectionLayoutSectionOrthogonalScrollingBehavior.None;
Same, it can be done with a switch.

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollBehaviorViewController.cs
> +			cell!.Label!.Text = $"{indexPath.Section}, {indexPath.Row}";
Can you check is not null before and not use !?

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +			cell!.Label!.Text = $"{indexPath.Section}, {indexPath.Row}";
Same.

2022-01-07 17:18 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceNewsFeedViewController.cs
> +			cell!.TitleLabel!.Text = newsItem?.Title;
Same.

2022-01-10 15:42 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +			// Populate the cell with our item description.
Does this seem sufficient?
```
if (cell is null || cell.Label is null)
	throw new NotImplementedException ("cell or cell.Label");
```

2022-01-10 20:57 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Basics View Controllers/DistinctSectionsViewController.cs
> +		return section is not null ? new UICollectionViewCompositionalLayout(SectionProviderHandler!) : null;
I think this is a little better:
```
if (SectionProviderHandler != null)
	return new UICollectionViewCompositionalLayout (SectionProviderHandler!);

return null;
```

2022-01-10 22:26 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollBehaviorViewController.cs
> +			return Unknown;
Hmm, the switch cases say that it expects constant values. I could do something like this though:
https://gist.github.com/tj-devel709/ca715ec69712645d210a9e1934a47b4e

2022-01-12 03:46 UTC, mandel-macaque requested changes
Lots of little cleanups to do, i have not gone through everything because I can see the same patterns over an over, please find the culprits that I have missed :)

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/AppDelegate.cs
> +	}
Do you need the get?

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +			throw new InvalidOperationException ("View");
use nameof https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +			throw new InvalidOperationException ("collectionView");
samle

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/NestedGroupsViewController.cs
> +			// Populate the cell with our item description.
Best way, rather than using the as operator, use the is operator which will do the check, this was added in c#7 that way there is not need to check if cell is null

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollBehaviorViewController.cs
> +			var cell = collectionView.DequeueReusableCell (TextCell.Key, indexPath) as TextCell;
same, the is operator should simplify things.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +			throw new InvalidOperationException ("View");
nameof

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +			throw new InvalidOperationException ("collectionView");
nameof

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +		var sections = Enumerable.Range (0, 5).Select (i => NSNumber.FromInt32 (i)).ToArray ();
IS the ToArray needed? Seems to be that we are getting an IEnumerable, so we should be able to loop with the foreach.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +		foreach (var section in sections) {
@chamons  you were right in the sense that the foreach change is smelly in this case, the ToArray is not needed if we use a foreach since it is a IEnumerable, your spidysenses were right.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +			var items = Enumerable.Range (idOffset, itemsPerSection).Select (i => NSNumber.FromInt32 (i)).ToArray ();
Do we need the toArray, does AppledItems take an IEnumerable?

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +				throw new InvalidOperationException ("cell or cell.Label");
ambiguous, that would be a pain to see when debugging, and the is operator will make it better like in the other comments.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceNewsFeedViewController.cs
> +			var newsItem = obj as ConferenceNewsController.NewsFeedItem;
is operator, get all the ? out no need.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceNewsFeedViewController.cs
> +			if (cell is null || cell.TitleLabel is null || cell.BodyLabel is null || cell.DateLabel is null)
Should be cleaner with the is operator.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceNewsFeedViewController.cs
> +				throw new InvalidOperationException ("cell, cell.Label, cell.BodyLabel, or cell.DateLabel");
be precise in exceptions like I mentioned above, but I'd be surprise you need it after the switch to is.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceVideoSessionsViewController.cs
> +			throw new InvalidOperationException ("View");
nameof

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceVideoSessionsViewController.cs
> +			throw new InvalidOperationException ("collectionView");
nameof

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceVideoSessionsViewController.cs
> +			foreach (var videoCollection in videosController.Collections!)
is ! needed at all? You did check for it not to be null.

2022-01-12 03:46 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/App Samples View Controllers/ConferenceVideoSessionsViewController.cs
> +			if (cell is null || cell.TitleLabel is null || cell.CategoryLabel is null)
Same as all the other comments.

2022-01-14 16:00 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Compositional Layout/Advanced Layouts View Controllers/OrthogonalScrollingViewController.cs
> +			var items = Enumerable.Range (idOffset, itemsPerSection).Select (i => NSNumber.FromInt32 (i)).ToArray ();
The AppendItems unfortunately does not take IEnumerable

2022-01-14 22:19 UTC, stephen-hawley commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/OutlineItemCell.cs
> +global using static Conference_Diffable.AppDelegate;
I've been putting all the `global using` declarations into one file named `GlobalUsings.cs`

2022-01-17 14:18 UTC, rolfbjarne approved these changes

2022-01-18 15:38 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/OutlineItemCell.cs
> +global using static Conference_Diffable.AppDelegate;
That's a great idea!

2022-01-19 16:20 UTC, mandel-macaque requested changes
some changes to make it more modern.

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/Cells And Supplementary Views/LabelCell.cs
> +		Layer.BorderColor = UIColor.SystemGray2Color.CGColor;
Can we move this to the label creation like you do in like 13?

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/InsertionSortViewController.cs
> +			if (section.Sorted) continue;
I believe the mono style is against this.

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/InsertionSortViewController.cs
> +		if (!sorting) return;
I believe the mono style is against this.

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/InsertionSortViewController.cs
> +			if (sorting) PerformSortStep ();
I believe the mono style is against this.

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/WIFIController.cs
> +			if (AvailableNetworks is not null) updatedNetworks.AddRange (AvailableNetworks);
I believe the mono style is against this.

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/WiFiSettingsViewController.cs
> +				var configItems = new List<ItemType> (new [] { ItemType.CurrentNetwork, ItemType.WifiEnabled });
We are creating a new list for every property get, we do not need that. Think a way of getting that content out.

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/OutlineViewController.cs
> +		collectionView.RegisterClassForCell (typeof (OutlineItemCell), OutlineItemCell.Key);
Property init in line 143

2022-01-19 16:20 UTC, mandel-macaque commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/OutlineViewController.cs
> +			throw new InvalidOperationException ("OutlineItem");
funny indentation.

2022-01-19 23:06 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/Cells And Supplementary Views/LabelCell.cs
> +		Layer.BorderColor = UIColor.SystemGray2Color.CGColor;
I think this Layer is coming from somewhere else and is not being created in this class

2022-01-19 23:07 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/InsertionSortViewController.cs
> +			if (section.Sorted) continue;
I don't like this either. It is against TJ style

2022-01-19 23:15 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Diffable/WiFiSettingsViewController.cs
> +				var configItems = new List<ItemType> (new [] { ItemType.CurrentNetwork, ItemType.WifiEnabled });
Hmm yeah that is a weird way to check that

2022-01-21 16:07 UTC, tj-devel709 commented on dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources/Conference-Diffable/Conference-Diffable.csproj
> +    <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
I need to see if I can get this running on iOS 13 as well, but will need to figure out how to get a simulator with iOS 13 running first

2022-01-25 01:09 UTC, mandel-macaque approved these changes

2022-01-25 14:49 UTC, merged