[Dotnet] Porting GroupedNotifications
xamarin/ios-samples pull request #430
Opened 2022-01-11 17:54 UTC by tj-devel709

This port required changing `UNNotificationPresentationOptions.Alert` (deprecated in iOS 14) to `UNNotificationPresentationOptions.List` and `UNNotificationPresentationOptions.Banner` instead making this sample actually require iOS 14!

2022-01-11 19:02 UTC, stephen-hawley requested changes

2022-01-11 19:02 UTC, stephen-hawley commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +        string message = "Fine!";
`var message`

2022-01-11 22:34 UTC, tj-devel709 commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/GroupedNotifications.csproj
> +    <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
Ah I mentioned in the description that I had to change UNNotificationPresentationOptions.Alert (deprecated in iOS 14) to UNNotificationPresentationOptions.List and UNNotificationPresentationOptions.Banner instead which made this sample actually require iOS 14!

Have you run into this issue where things deprecate in iOS 14?

2022-01-12 04:03 UTC, mandel-macaque requested changes

2022-01-12 04:03 UTC, mandel-macaque commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +        var author = friend ?? throw new InvalidOperationException ("friend");
Throwing an exception in a async void method is not very useful: https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void so we might just log and return doing nothing.

The important detail, log, or else we won't know (please read carefully the doc and ask me question if you have them).

2022-01-12 04:03 UTC, mandel-macaque commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +            ThreadIdentifier = threadId ?? throw new InvalidOperationException ("threadId"),
Same. I'm going to guess this is not your code 🤦

2022-01-14 22:58 UTC, tj-devel709 commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +        var author = friend ?? throw new InvalidOperationException ("friend");
So a simple Console.Log here for these exceptions? In the article it looks like an option could be to call a new async method that returns a Task and have that method throw an exception?

2022-01-14 22:58 UTC, tj-devel709 commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +            ThreadIdentifier = threadId ?? throw new InvalidOperationException ("threadId"),
Eh I added the Exception haha

2022-01-17 14:25 UTC, rolfbjarne approved these changes

2022-01-18 14:18 UTC, stephen-hawley approved these changes

2022-01-19 15:54 UTC, mandel-macaque commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +        var author = friend ?? throw new InvalidOperationException ("friend");
Use a Console.Log since you cannot return a task in a delegate, it is a dirty corner in the lang.

2022-01-20 16:27 UTC, tj-devel709 commented on dotnet/ios/ios12/GroupedNotifications/GroupedNotifications/ViewController.cs
> +        var author = friend ?? throw new InvalidOperationException ("friend");
Even better, I just made the string non-nullable so I don't need to do these checks!

2022-01-20 16:28 UTC, tj-devel709 commented
I need to figure out how to run on iOS 12 - iOS 13 to test the alert system support, but currently having trouble getting that iOS version in VSMac 2022 Preview. Looking into running on cli

2022-01-21 19:13 UTC, tj-devel709 commented
This one is working on a simulator running iOS 12! 
Good to merge once approved!

2022-01-25 01:15 UTC, mandel-macaque approved these changes

2022-01-25 14:50 UTC, merged