[Dotnet] Porting XamarinNL
xamarin/ios-samples pull request #431
Opened 2022-01-11 19:59 UTC by tj-devel709

2022-01-11 21:08 UTC, stephen-hawley requested changes

2022-01-11 21:08 UTC, stephen-hawley commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +        var cell = TableView.DequeueReusableCell (LanguageProbabilityCell);
`var cell = TableView.DequeueReusableCell (LanguageProbabilityCell) ?? throw new InvalidOperationException (nameof (cell));`

2022-01-11 22:47 UTC, tj-devel709 commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +        var cell = TableView.DequeueReusableCell (LanguageProbabilityCell);
Looks like I have to use `"cell"` instead of `nameof (cell)` since cell is not declared yet

2022-01-12 04:04 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +        var cell = TableView.DequeueReusableCell (LanguageProbabilityCell);
@tj-devel709  correct, rather split it in two, assign then an if.

2022-01-12 04:09 UTC, mandel-macaque requested changes
We need to clean the code, i'm sure most of it is inherited from the old code.

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +    NSString[]? sortedLanguages;
Remove the nullability, initially with Array.Empty and you'll make your life better without the need to check for null.

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +        NLLanguage language = NLLanguageExtensions.GetValue (languageAbbreviation);
use var, lets be consistent.

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageRecognizerViewController.cs
> +        var destination = segue.DestinationViewController as LanguageProbabilityTableViewController;
is operator, makes your life easier, no need to the next check for null.

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTaggerViewController.cs
> +        var destination = segue.DestinationViewController as LanguageTaggerTableViewController;
use the is operator.

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTaggerViewController.cs
> +            tagger.String = UserInput.Text;
move one line up, merge as a property init in the constructor.

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerTableViewController.cs
> +    public NSValue[]? Tokens { get; set; }
Array.Empty

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerTableViewController.cs
> +		{
there is something wrong with your indentation (@rolfbjarne  dixit to me once and hurt my feelings)

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerViewController.cs
> +    NSValue[]? tokens;
ArrayEmpty?

2022-01-12 04:09 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerViewController.cs
> +        var destination = segue.DestinationViewController as LanguageTokenizerTableViewController;
Use te is operator.

2022-01-12 12:43 UTC, rolfbjarne approved these changes

2022-01-12 12:43 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTaggerTableViewController.cs
> +    public LanguageTaggerTableViewController (IntPtr handle) : base (handle) { }
```suggestion
    protected LanguageTaggerTableViewController (IntPtr handle) : base (handle) { }
```

2022-01-12 12:43 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTaggerViewController.cs
> +    public LanguageTaggerViewController (IntPtr handle) : base (handle) { }
```suggestion
    protected LanguageTaggerViewController (IntPtr handle) : base (handle) { }
```

2022-01-12 12:43 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerTableViewController.cs
> +    public LanguageTokenizerTableViewController (IntPtr handle) : base (handle) { }
```suggestion
    protected LanguageTokenizerTableViewController (IntPtr handle) : base (handle) { }
```

2022-01-12 12:43 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerTableViewController.cs
> +		{
🤕

2022-01-12 12:43 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerViewController.cs
> +    public LanguageTokenizerViewController (IntPtr handle) : base (handle) { }
```suggestion
    protected LanguageTokenizerViewController (IntPtr handle) : base (handle) { }
```

2022-01-21 16:08 UTC, tj-devel709 commented on dotnet/ios/ios12/XamarinNL/XamarinNL/XamarinNL.csproj
> +    <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
Need to get this running on iOS 12 but first need to figure out how to get a simulator running iOS 12

2022-01-21 21:49 UTC, tj-devel709 commented
Okay runs on iOS 12 now, ready to merge after getting the thumbs up

2022-01-25 01:20 UTC, mandel-macaque approved these changes
Please use nameof before landing but it does not deserve a block for that.

2022-01-25 01:20 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +		throw new InvalidOperationException ("UITableViewCell");
nameof

2022-01-25 01:20 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageRecognizerViewController.cs
> +			if (probabilities is not null)
lets use an and here and merge it with the previos if, we reduce the indentation and is nicer.

2022-01-25 01:20 UTC, mandel-macaque commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageTokenizerTableViewController.cs
> +		throw new InvalidOperationException ("UICollectionViewCell");
nameof

2022-01-25 14:56 UTC, tj-devel709 commented on dotnet/ios/ios12/XamarinNL/XamarinNL/LanguageProbabilityTableViewController.cs
> +		throw new InvalidOperationException ("UITableViewCell");
Oh awesome, I didn't know I could do nameof for types!

2022-01-25 15:03 UTC, merged