port of ARKitVision to dotnet
xamarin/ios-samples pull request #432
Opened 2022-01-11 20:58 UTC by stephen-hawley

2022-01-11 22:28 UTC, tj-devel709 commented on dotnet/ios/ios12/ARKitVision/ARKitVision/Utilities.cs
> +public static string GetPresentationString(this ARCamera self)
I think an indent got lost here

2022-01-11 22:30 UTC, tj-devel709 commented on dotnet/ios/ios12/ARKitVision/ARKitVision/Utilities.cs
> +﻿using ARKit;
I think it would make sense to use the `global using ARKit` for ARKit and maybe a few others (maybe not) would be good in one file since it looks like it is used everywhere! But just a style choice

2022-01-11 22:30 UTC, tj-devel709 approved these changes
After that spacing issue, it looks good to me!

2022-01-12 04:10 UTC, mandel-macaque commented on dotnet/ios/ios12/ARKitVision/ARKitVision/StatusViewController.cs
> +        public Action RestartExperienceHandler { get; set; } = () => { };
cute

2022-01-12 04:13 UTC, mandel-macaque requested changes
LGTM yet I agree with @tj-devel709  there are some weird indentations login on, maybe a tabs vs spaces situation.

2022-01-12 04:13 UTC, mandel-macaque commented on dotnet/ios/ios12/ARKitVision/ARKitVision/StatusViewController.cs
> +                         {
funny indentation.

2022-01-12 04:13 UTC, mandel-macaque commented on dotnet/ios/ios12/ARKitVision/ARKitVision/StatusViewController.cs
> +                 {
Same.

2022-01-12 04:13 UTC, mandel-macaque commented on dotnet/ios/ios12/ARKitVision/ARKitVision/StatusViewController.cs
> +                 {
Same.

2022-01-12 04:13 UTC, mandel-macaque commented on dotnet/ios/ios12/ARKitVision/ARKitVision/Utilities.cs
> +        case ARTrackingState.Limited:
A switch with a single case with a nested switch. I suppose we inherited this 🤦

2022-01-12 11:21 UTC, rolfbjarne approved these changes

2022-01-12 11:21 UTC, rolfbjarne commented on dotnet/ios/ios12/ARKitVision/ARKitVision/Info.plist
> +	<string>12.0</string>
This can be removed (we use the `SupportedOSPlatformVersion` value from the csproj instead):

```suggestion
```

2022-01-12 11:21 UTC, rolfbjarne commented on dotnet/ios/ios12/ARKitVision/ARKitVision/StatusViewController.cs
> +        public StatusViewController (IntPtr handle) : base (handle) { }
This doesn't have to be public:

```suggestion
        protected StatusViewController (IntPtr handle) : base (handle) { }
```

2022-01-12 11:21 UTC, rolfbjarne commented on dotnet/ios/ios12/ARKitVision/ARKitVision/ViewController.cs
> +                         }
This is really a style choice, but another alternative is:

```suggestion
                         currentBuffer?.Dispose ();
                         currentBuffer = null;
```

2022-01-12 11:21 UTC, rolfbjarne commented on dotnet/ios/ios12/ARKitVision/ARKitVision/ViewController.cs
> +                if (classifications == null)
```suggestion
                if (classifications is null)
```

2022-01-12 11:21 UTC, rolfbjarne commented on dotnet/ios/ios12/ARKitVision/ARKitVision/ViewController.cs
> +                if (bestResult != null)
```suggestion
                if (bestResult is not null)
```

2022-01-12 16:50 UTC, mandel-macaque approved these changes
You need to set the editor settings to do the right things with the indentation.

2022-01-12 16:50 UTC, mandel-macaque commented on dotnet/ios/ios12/ARKitVision/ARKitVision/ViewController.cs
> +                 {
Your editor setting are wrong.

2022-01-12 17:37 UTC, merged